# -*- coding: utf-8 -*-
"""Pywhatkit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ta1_djcvoIOIk7NHE2sl8tEH8rhRfoeQ
"""

# Installing the library

!pip install pywhatkit

"""[link text](https://pywhatkit.herokuapp.com/)

# Sending WhatsApp Message

**pywhatkit is a Python library for sending WhatsApp messages at a certain time, it has several other features too.

Following are some features of pywhatkit module:

-> Send WhatsApp messages.
-> Play a YouTube video.
-> Perform a Google Search.
->Get information on a particular topic.

The pywhatkit module can also be used for converting text into handwritten text images**

# **Syntax: pywhatkit.sendmsg(“receiver mobile number”,”message”,hours,minutes)

Parameters:

Receiver mobile number: The Receiver’s mobile number must be in string format and the country code must be mentioned before the mobile number.
Message: Message to be sent(Must be in string format).
Hours: This module follows the 24 hrs time format.
Minutes: Mention minutes of the scheduled time for the message(00-59).**
"""

import pywhatkit as pt
# Send a WhatsApp Message to a Contact at 1:30 PM
pt.sendwhatmsg("+916268811789", "hi", 13, 30)

# Same as above but Closes the Tab in 2 Seconds after Sending the Message
pt.sendwhatmsg("+916268811789", "Hello", 13, 30, 15, True, 2)

# Send an Image to a Group with the Caption as Hello
pt.sendwhats_image("illuminates", "Images/Hello.png", "Hello")

# Send an Image to a Contact with the no Caption
pt.sendwhats_image("+916268811789", "Images/Hello.png")

# Send a WhatsApp Message to a Group at 12:00 AM
pt.sendwhatmsg_to_group("illuminates", "Hey All!", 0, 0)

# Send a WhatsApp Message to a Group instantly
pt.sendwhatmsg_to_group_instantly("illuminates", "Hey All!")

# Play a Video on YouTube
pt.playonyt("PyWhatKit")

import pywhatkit as pwk
 
# using Exception Handling to avoid unexpected errors
try:
     # sending message in Whatsapp in India so using Indian dial code (+91)
     pwk.sendwhatmsg("+916268811789", "Hi, how are you?", 20, 34)
 
     print("Message Sent!") #Prints success message in console
 
     # error message
except: 
     print("Error in sending the message")

"""*phone_num (required) - Phone number of target with country code
message (required) - Message that you want to sendwhatmsg
time_hour (required) - Hours at which you want to send message in 24 hour format
time_min (required) - Minutes at which you want to send message
wait_time (optional, val=20) - Seconds after which the message will be sent after opening the web
print_waitTime (optional, val=True) - Will print the remaining time if set to true*

#  Play a YouTube video

**Function pywhatkit.playonyt(), opens the YouTube in your default browser and plays the video you mentioned in the function. If you pass the topic name as parameter, it plays the random video on that topic. On passing the URL of the video as the parameter, it open that exact video.

Syntax: pywhatkit.playonyt(“url/topic name”)

Parameters: 

URL/Topic Name: Mention the topic name or URL of the YouTube video**
"""

# importing the module
import pywhatkit as pt

# using Exception Handling
# to avoid exceptions
try:
  pt.playonyt("Shape of You song")
  print("Playing...")

except:
  print("Network Error Occurred")

"""*pt.search() :- This function can be used to make a google search for any term

pt.info():- This function can be used to fetch information about any topic

Parameters:-> topic (required) - Topic or title that you want to get information about
lines (optional, val=3) - Number of lines that you want to print about it*

**pt.image_to_ascii_art() :- This function can be used to convert any image to ASCII art
Parameters:- imgpath (required) - Path to the image that you want to convert
output_file (optional, val=pywhatkit_asciiart.txt") - File where you want to save the output characters**

**pt.text_to_handwriting() :- This function can be used to convert text to hand written characters, the character sets has been written by me**
"""



"""#  Perform Google Search:"""

# importing the module
import pywhatkit

# use Try Except to
# handle the Exceptions
try:

# it will perform the Google search
pywhatkit.search("Python")
print("Searching...")

except:

# Printing Error Message
print("An unknown error occurred")

"""# Get information on  particular topic: """

# importing the module
import pywhatkit

# using Exception Handling for
# handling unprecedented errors
try:

# it will perform google search
pywhatkit.info("Google", lines = 4)
print("\nSuccessfully Searched")

except:
	
# printing error message
print("An Unknown Error Occurred")

"""# Thank You"""